[toolchain]
anchor_version = "1.2.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gateproof = "Fg6PaFpoGXkYsidMpWxTWqkZL7FEfcYkgMQhgB9qL5p"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/gateproof"]

[scripts]
test = "pnpm test"
