[package]
name = "gateproof"
version = "0.1.0"
description = "On-chain ticket lifecycle registry for GateProof"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gateproof"

[features]
default = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "1.1.2"
